services: 
  postgres:
    image: postgres:15
    container_name: cars_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    networks:
      - cars_network

  app:
    build: .
    container_name: cars_extractor
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    extra_hosts:
    - "host.docker.internal:host-gateway"
    networks:
      - cars_network

  airflow:
    image: apache/airflow:2.8.1-python3.11
    container_name: cars_airflow
    user: "${AIRFLOW_UID:-1000}:0"
    command: standalone
    volumes:
      - .:/opt/airflow # Mount project so Airflow sees your scripts and dbt
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://vinicius:admin123@postgres:5432/cars_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow
      - _PIP_ADDITIONAL_REQUIREMENTS=dbt-postgres==1.7.0 protobuf==4.25.3
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - cars_network


networks:
  cars_network:
    driver: bridge